/* https://school.programmers.co.kr/learn/courses/30/lessons/131118 */

SELECT
    A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE), 2) as SCORE
FROM
    REST_INFO as A JOIN REST_REVIEW as B on A.REST_ID = B.REST_ID
WHERE
    A.ADDRESS LIKE '서울%'
GROUP BY
    A.REST_ID
ORDER BY
    SCORE DESC, A.FAVORITES DESC